//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_KT5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int Id { get; set; }
        public int Role { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string PastName { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string Passport { get; set; }
        public string BirthDate { get; set; }
        public string LastEnter { get; set; }
        public Nullable<int> Enter { get; set; }
        public int Sex { get; set; }
    }
}
